# Generated by Django 4.2.7 on 2026-08-13 14:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_email', models.CharField(max_length=255)),
                ('actor_type', models.CharField(choices=[('citizen', 'Citizen'), ('official', 'Official'), ('system', 'System')], max_length=20)),
                ('action', models.CharField(max_length=100)),
                ('resource_type', models.CharField(max_length=100)),
                ('resource_id', models.CharField(max_length=255)),
                ('note', models.TextField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['actor_email'], name='audit_logs_actor_e_f3ef0d_idx'), models.Index(fields=['action'], name='audit_logs_action_31f574_idx'), models.Index(fields=['resource_type'], name='audit_logs_resourc_e11e1b_idx'), models.Index(fields=['created_at'], name='audit_logs_created_262184_idx')],
            },
        ),
    ]
