# Generated by Django 4.2.7 on 2026-08-08 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusupdate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_status_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='statusupdate',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_updates', to='incidents.incidentcluster'),
        ),
        migrations.AddField(
            model_name='incidentcluster',
            name='source_reports',
            field=models.ManyToManyField(related_name='incident_clusters', to='reports.report'),
        ),
        migrations.AddField(
            model_name='aiseverityprediction',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_severity_predictions', to='incidents.incidentcluster'),
        ),
        migrations.AddField(
            model_name='aicredibilityscore',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_credibility_scores', to='incidents.incidentcluster'),
        ),
    ]
