# Generated by Django 4.2.7 on 2026-08-12 09:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_remove_report_severity_report_idempotency_key_and_more'),
        ('resources', '0004_officialaccount_full_name'),
        ('incidents', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incidentcluster',
            options={'ordering': ['-opened_at']},
        ),
        migrations.AlterModelOptions(
            name='statusupdate',
            options={'ordering': ['-updated_at']},
        ),
        migrations.RemoveField(
            model_name='aicredibilityscore',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='aicredibilityscore',
            name='score',
        ),
        migrations.RemoveField(
            model_name='aiseverityprediction',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='aiseverityprediction',
            name='predicted_severity',
        ),
        migrations.RemoveField(
            model_name='incidentcluster',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='statusupdate',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='statusupdate',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='statusupdate',
            name='message',
        ),
        migrations.RemoveField(
            model_name='statusupdate',
            name='status',
        ),
        migrations.AddField(
            model_name='aicredibilityscore',
            name='ai_was_correct',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aicredibilityscore',
            name='computed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='aicredibilityscore',
            name='feature_inputs',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='aicredibilityscore',
            name='score_level',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='aicredibilityscore',
            name='score_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiseverityprediction',
            name='computed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='aiseverityprediction',
            name='predicted_level',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='aiseverityprediction',
            name='probability_critical',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='aiseverityprediction',
            name='probability_high',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='aiseverityprediction',
            name='probability_low',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='aiseverityprediction',
            name='probability_medium',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='incidentcluster',
            name='actual_severity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidentcluster',
            name='center_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidentcluster',
            name='center_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidentcluster',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidentcluster',
            name='opened_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='incidentcluster',
            name='report_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='incidentcluster',
            name='witness_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statusupdate',
            name='new_status',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='statusupdate',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='statusupdate',
            name='old_status',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='statusupdate',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='statusupdate',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_status_updates', to='resources.officialaccount'),
        ),
        migrations.AlterField(
            model_name='aicredibilityscore',
            name='model_version',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='aiseverityprediction',
            name='confidence',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='aiseverityprediction',
            name='model_version',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='incidentcluster',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='incidentcluster',
            name='source_reports',
            field=models.ManyToManyField(blank=True, related_name='incident_clusters', to='reports.report'),
        ),
        migrations.AlterField(
            model_name='incidentcluster',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('active', 'Active'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('closed', 'Closed')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='incidentcluster',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
