# Generated by Django 4.2.7 on 2026-08-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0003_alter_incidentcluster_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentcluster',
            name='report_type',
            field=models.CharField(blank=True, choices=[('accident', 'Accident'), ('fire', 'Fire'), ('medical', 'Medical'), ('flood', 'Flood'), ('security', 'Security'), ('hazmat', 'HazMat'), ('weather', 'Weather'), ('sos', 'SOS'), ('other', 'Other')], max_length=30, null=True),
        ),
    ]
