# Generated by Django 4.2.7 on 2026-08-08 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('priority', models.CharField(default='normal', max_length=20)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('assigned', 'Assigned'), ('en_route', 'En Route'), ('arrived', 'Arrived'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='requested', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dispatch_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResourceAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('eta_minutes', models.IntegerField(default=0)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'dispatch_resource_assignment',
            },
        ),
    ]
