# Generated by Django 4.2.7 on 2026-08-08 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0001_initial'),
        ('incidents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dispatch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourceassignment',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resourceassignment',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_assignments', to='dispatch.dispatchrequest'),
        ),
        migrations.AddField(
            model_name='resourceassignment',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='resources.fieldunit'),
        ),
        migrations.AddField(
            model_name='dispatchrequest',
            name='assigned_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_requests', to='resources.fieldunit'),
        ),
        migrations.AddField(
            model_name='dispatchrequest',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_requests', to='incidents.incidentcluster'),
        ),
        migrations.AddField(
            model_name='dispatchrequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_dispatches', to=settings.AUTH_USER_MODEL),
        ),
    ]
