# Generated by Django 4.2.7 on 2026-08-12 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0004_incidentcluster_report_type'),
        ('dispatch', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourceassignment',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_assignments', to='incidents.incidentcluster'),
        ),
        migrations.AddField(
            model_name='resourceassignment',
            name='justification',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='resourceassignment',
            name='priority_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resourceassignment',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_assignments', to='dispatch.dispatchrequest'),
        ),
    ]
