# Generated by Django 4.2.7 on 2026-08-12 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_officialaccount_full_name'),
        ('dispatch', '0003_resourceassignment_cluster_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourceassignment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resourceassignment',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resourceassignment',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_assignments', to='resources.officialaccount'),
        ),
    ]
