# Generated by Django 4.2.7 on 2026-08-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0004_resourceassignment_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceassignment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('suggested', 'Suggested'), ('confirmed', 'Confirmed'), ('dispatched', 'Dispatched'), ('completed', 'Completed'), ('overridden', 'Overridden'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
