name: nidaa_app
description: نداء - تطبيق الإبلاغ عن الطوارئ
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  connectivity_plus: ^6.0.3
  dio: ^5.4.0
  flutter_local_notifications: ^22.3.0
  flutter_map: ^8.0.0
  flutter_map_tile_caching: ^10.1.1
  flutter_secure_storage: ^11.0.0
  geolocator: ^14.0.3
  get: ^4.7.2
  image_picker: ^1.0.4
  latlong2: ^0.9.1
  path_provider: ^2.1.4
  pinput: ^6.0.0
  record: ^6.2.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.3.2
  web_socket_channel: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.1

dependency_overrides:
  smart_auth: ^3.2.0

flutter_launcher_icons:
  android: true
  ios: false
  image_path: assets/images/app_icon.jpg
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: assets/images/app_icon.jpg

flutter:
  uses-material-design: true
  assets:
    - assets/images/
