# Generated by Django 4.2.7 on 2026-08-08 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrisisSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('region', models.CharField(default='all', max_length=120)),
                ('total_reports', models.IntegerField(default=0)),
                ('open_incidents', models.IntegerField(default=0)),
                ('resolved_incidents', models.IntegerField(default=0)),
                ('avg_severity', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'analytics_crisis_summary',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ResponseMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(max_length=80)),
                ('metric_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='analytics.crisissummary')),
            ],
            options={
                'db_table': 'analytics_response_metric',
            },
        ),
    ]
