# Generated by Django 4.2.7 on 2026-08-12 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_initial'),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentReportSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_severity', models.IntegerField(blank=True, null=True)),
                ('response_time_minutes', models.FloatField(blank=True, null=True)),
                ('total_reports', models.IntegerField(default=0)),
                ('total_witnesses', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incident', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report_summary', to='incidents.incidentcluster')),
            ],
            options={
                'db_table': 'analytics_incident_report_summary',
            },
        ),
    ]
