# Generated by Django 4.2.7 on 2026-08-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_incidentreportsummary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidentreportsummary',
            name='final_severity',
        ),
        migrations.AddField(
            model_name='incidentreportsummary',
            name='actual_severity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidentreportsummary',
            name='ai_predicted_severity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidentreportsummary',
            name='citizen_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidentreportsummary',
            name='citizen_reported_severity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidentreportsummary',
            name='false_report',
            field=models.BooleanField(default=False),
        ),
    ]
