# Generated by Django 4.2.7 on 2026-08-08 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='severity',
        ),
        migrations.AddField(
            model_name='report',
            name='idempotency_key',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='report',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='reported_severity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='report',
            name='submission_method',
            field=models.CharField(default='form', max_length=30),
        ),
        migrations.AddField(
            model_name='report',
            name='victims_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='report',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('accident', 'Accident'), ('fire', 'Fire'), ('medical', 'Medical'), ('flood', 'Flood'), ('security', 'Security'), ('hazmat', 'HazMat'), ('weather', 'Weather'), ('sos', 'SOS'), ('other', 'Other')], default='other', max_length=30),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='received', max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='witnessreport',
            name='statement',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='witnessreport',
            name='witness_name',
            field=models.CharField(blank=True, default='Anonymous', max_length=150),
        ),
    ]
