# Generated by Django 4.2.7 on 2026-08-12 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0004_incidentcluster_report_type'),
        ('reports', '0003_remove_report_severity_report_idempotency_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cluster_reports', to='incidents.incidentcluster'),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('under_review', 'Under Review'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('rejected', 'Rejected'), ('closed', 'Closed')], default='received', max_length=20),
        ),
    ]
