# Generated by Django 4.2.7 on 2026-08-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_report_cluster_alter_report_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('under_review', 'Under Review'), ('pending_transcription', 'Pending Transcription'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('rejected', 'Rejected'), ('closed', 'Closed')], default='received', max_length=30),
        ),
        migrations.AlterField(
            model_name='voicerecord',
            name='transcript',
            field=models.TextField(blank=True, null=True),
        ),
    ]
