# Generated by Django 4.2.7 on 2026-08-14 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('incidents', '0004_incidentcluster_report_type'),
        ('reports', '0005_alter_report_status_alter_voicerecord_transcript'),
    ]

    operations = [
        migrations.AddField(
            model_name='witnessreport',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='witness_reports', to='incidents.incidentcluster'),
        ),
        migrations.AddField(
            model_name='witnessreport',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='witnessreport',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='witnessreport',
            name='photo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='witnessreport',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='witness_statements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='witnessreport',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='witness_reports', to='reports.report'),
        ),
    ]
