# Generated by Django 4.2.7 on 2026-08-12 09:17

from django.db import migrations, models
import django.db.models.deletion


def seed_access_roles(apps, schema_editor):
    AccessRole = apps.get_model('resources', 'AccessRole')
    AccessRole.objects.get_or_create(name='admin', defaults={'permissions': {'all': True}})
    AccessRole.objects.get_or_create(name='operator', defaults={'permissions': {'dispatch': True, 'view': True}})
    AccessRole.objects.get_or_create(name='viewer', defaults={'permissions': {'view': True}})


def seed_unit_types(apps, schema_editor):
    UnitType = apps.get_model('resources', 'UnitType')
    for name in ['ambulance', 'fire_truck', 'rescue_team', 'shelter']:
        UnitType.objects.get_or_create(name=name)


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('permissions', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'resources_access_role',
            },
        ),
        migrations.RemoveField(
            model_name='fieldunit',
            name='unit_id',
        ),
        migrations.RemoveField(
            model_name='officialaccount',
            name='user',
        ),
        migrations.AddField(
            model_name='fieldunit',
            name='call_sign',
            field=models.CharField(default='', max_length=80, unique=True),
        ),
        migrations.AddField(
            model_name='fieldunit',
            name='current_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldunit',
            name='current_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldunit',
            name='last_location_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='officialaccount',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='officialaccount',
            name='password_hash',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='fieldunit',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('out_of_service', 'Out of Service')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='officialaccount',
            name='designation',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='officialaccount',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='official_accounts', to='resources.accessrole'),
        ),
        migrations.RunPython(seed_access_roles, migrations.RunPython.noop),
        migrations.RunPython(seed_unit_types, migrations.RunPython.noop),
    ]
