# Generated by Django 4.2.7 on 2026-08-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_seed_resources'),
    ]

    operations = [
        migrations.AddField(
            model_name='officialaccount',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
